language: android
sudo: false
jdk: oraclejdk8

android:
  components:
    - tools
    - tools # Include again to work around travis not using the latest.
            # https://github.com/travis-ci/travis-ci/issues/6193
            # Required to get the newest platform-tools.
    - platform-tools
    - build-tools-26.0.2
    - android-26
  licenses:
    - '.+'
before_script:
    - chmod +x gradlew
script:
    - ./gradlew build
after_failure:
    - cat build/reports/lint-results.xml
    - cat build/outputs/lint-results-debug.xml
    - cd ../..
    - pwd
    - ls -la $HOME
    - ls -la $HOME/android-sdk